using Content.Client.UserInterface.Controls;
using Content.Shared._CorvaxNext.ModularComputers;
using Content.Shared._CorvaxNext.ModularComputers.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CorvaxNext.ModularComputers.UI;

[GenerateTypedNameReferences]
public sealed partial class ModularComputerUI : FancyWindow
{
    [Dependency] private IEntityManager _entManager = null!;
    private ModularComputersSystem _modComps;

    public ModularComputerUI()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _modComps = _entManager.System<ModularComputersSystem>();
    }

    public void Initialize(EntityUid modcomp)
    {
        var mod = _entManager.GetComponent<ModularComputerComponent>(modcomp);
        if (_modComps.TryGetPciComponent(mod, out PciGpuComponent? gpu, out _))
            GpuRender.GpuComponent = gpu;
    }
}

