using System.Buffers.Binary;
using System.IO;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CorvaxNext.ModularComputers.UI;

[GenerateTypedNameReferences]
public sealed partial class ProshivkaUI : FancyWindow
{
    [Robust.Shared.IoC.Dependency] private readonly IFileDialogManager _fileDialogManager = default!;
    private ProshivkaBoundUI _bui = null!;

    public ProshivkaUI()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void Initialize(ProshivkaBoundUI bui)
    {
        Button.OnButtonDown += OnProshivkaSelected;
        _bui = bui;
    }

    private async void OnProshivkaSelected(BaseButton.ButtonEventArgs args)
    {
        var file = _fileDialogManager.OpenFile();
        var stream = await file;
        if (stream == null)
            return;

        using var ms = new MemoryStream();
        await stream.CopyToAsync(ms);
        ms.Position = 0;
        var data = ms.ToArray();
        var sig = BinaryPrimitives.ReadUInt64LittleEndian(data);
        if (sig == 0x7F454C46 || sig == 0x464C457F)
            data = data.AsSpan().Slice(0x1000).ToArray();
        _bui.SendProgramm(data);

        Close();
    }
}

