using System.IO;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CorvaxNext.ModularComputers.UI;

[GenerateTypedNameReferences]
public sealed partial class ProshivkaUI : FancyWindow
{
    [Dependency] private readonly IFileDialogManager _fileDialogManager = default!;

    public ProshivkaUI()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void Initialize(ProshivkaBoundUI bui)
    {
        Button.OnButtonDown += (_) =>
        {
            var file = _fileDialogManager.OpenFile();
            var stream = file.GetAwaiter().GetResult()!;
            using (var ms = new MemoryStream())
            {
                stream.CopyTo(ms);
                bui.SendProgramm(ms.ToArray());
            }
        };
    }
}

