using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CorvaxNext.IntegratedCircuits.UI.Controls;

[GenerateTypedNameReferences]
public sealed partial class StringMemoryCircuitEditor : Control
{
    public StringMemoryCircuitEditor(ElectronicAssemblyBoundUserInterface bui, string text, NetEntity netEntity)
    {
        RobustXamlLoader.Load(this);
        var bui1 = bui;
        var entity = netEntity;
        MemoryContent.Text = text;
        SetButton.OnButtonDown += _ => bui1.SendChangeStringMemoryCircuitMessage(entity, MemoryContent.Text);
    }
}

